#!/bin/bash
# Warp terminal integration for worktree lifecycle.
#
# No-op when ~/.warp does not exist, so non-Warp users are unaffected.
#
# Functions:
#   warp_available                      0 if ~/.warp exists, 1 otherwise
#   warp_tab_config_path <wt_path>      Echoes target TOML path (deterministic)
#   warp_emit_tab_config <wt_path> <project> <branch> [ticket]
#                                       Writes 2-pane (claude + shell) TOML
#   warp_open_tab <wt_path>             open warp://action/new_tab?path=...
#   warp_remove_tab_config <wt_path>    rm -f TOML matching wt_path

WARP_DIR="${WARP_DIR:-$HOME/.warp}"
WARP_TAB_CONFIGS_DIR="${WARP_TAB_CONFIGS_DIR:-$WARP_DIR/tab_configs}"

warp_available() {
    [[ -d "$WARP_DIR" ]]
}

# Sanitize an arbitrary string for use in a filename: lowercase, replace any
# run of non-alphanumerics with a single hyphen, strip leading/trailing hyphens.
_warp_sanitize() {
    local raw="$1"
    printf '%s' "$raw" \
        | tr '[:upper:]' '[:lower:]' \
        | sed -e 's/[^a-z0-9]\{1,\}/-/g' -e 's/^-//' -e 's/-$//'
}

# Deterministic TOML path from worktree path. Basename is sanitized for a
# readable prefix; an 8-char hash of the absolute path is appended to avoid
# collisions between built-in worktrees with the same name in different
# projects (e.g. web/.claude/worktrees/spike vs ada/.claude/worktrees/spike).
warp_tab_config_path() {
    local wt_path="$1"
    local base hash id
    base="$(_warp_sanitize "$(basename "$wt_path")")"
    # cksum is POSIX and on every macOS/Linux; take the first field and hex it.
    hash="$(printf '%s' "$wt_path" | cksum | awk '{ printf "%08x", $1 }')"
    id="${base}-${hash}"
    printf '%s/wt-%s.toml' "$WARP_TAB_CONFIGS_DIR" "$id"
}

# TOML string escape: backslashes and double quotes.
_warp_toml_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '%s' "$s"
}

# Emit a 2-pane tab config (claude left, shell right) for the given worktree.
#   $1 worktree path (absolute)
#   $2 project name
#   $3 branch name
#   $4 ticket id (optional)
warp_emit_tab_config() {
    local wt_path="$1" project="$2" branch="$3" ticket="${4:-}"
    warp_available || return 0

    local target
    target="$(warp_tab_config_path "$wt_path")"
    if ! mkdir -p "$(dirname "$target")" 2>/dev/null; then
        echo "warp: could not create $(dirname "$target")" >&2
        return 1
    fi

    local wt_name
    wt_name="$(basename "$wt_path")"

    local esc_path esc_title esc_name
    esc_path="$(_warp_toml_escape "$wt_path")"
    esc_title="$(_warp_toml_escape "$project · $wt_name")"
    esc_name="$(_warp_toml_escape "wt: $wt_name")"

    local ticket_comment=""
    if [[ -n "$ticket" ]]; then
        ticket_comment="# Ticket: $ticket"$'\n'
    fi

    {
        printf '# Auto-generated by scripts/worktree/lib/worktree-warp.sh\n'
        printf '# Worktree: %s\n' "$wt_name"
        printf '# Branch:   %s\n' "$branch"
        [[ -n "$ticket_comment" ]] && printf '%s' "$ticket_comment"
        printf '# Removed automatically by worktree-done.sh\n\n'
        printf 'name = "%s"\n' "$esc_name"
        printf 'title = "%s"\n' "$esc_title"
        printf 'color = "blue"\n\n'
        printf '[[panes]]\n'
        printf 'id = "root"\n'
        printf 'split = "horizontal"\n'
        printf 'children = ["claude", "shell"]\n\n'
        printf '[[panes]]\n'
        printf 'id = "claude"\n'
        printf 'type = "terminal"\n'
        printf 'directory = "%s"\n' "$esc_path"
        printf 'commands = ["claude"]\n'
        printf 'is_focused = true\n\n'
        printf '[[panes]]\n'
        printf 'id = "shell"\n'
        printf 'type = "terminal"\n'
        printf 'directory = "%s"\n' "$esc_path"
    } > "$target" 2>/dev/null || { echo "warp: could not write $target" >&2; return 1; }

    return 0
}

# URL-encode a path for use in warp:// URI scheme. Preserves unreserved chars
# and "/" (path separator); percent-encodes everything else.
_warp_urlencode_path() {
    local s="$1" out="" i c
    for (( i=0; i<${#s}; i++ )); do
        c="${s:i:1}"
        case "$c" in
            [a-zA-Z0-9._~/-]) out+="$c" ;;
            *) printf -v out '%s%%%02X' "$out" "'$c" ;;
        esac
    done
    printf '%s' "$out"
}

# Best-effort: open a Warp tab at the worktree path via warp:// URI scheme.
# This opens a plain shell tab — the full 2-pane layout is available via the
# + menu entry created by warp_emit_tab_config.
# Returns 0 on successful launch, 1 if unavailable or launch failed.
warp_open_tab() {
    local wt_path="$1"
    warp_available || return 1
    command -v open >/dev/null 2>&1 || return 1

    local encoded
    encoded="$(_warp_urlencode_path "$wt_path")"
    open "warp://action/new_tab?path=$encoded" >/dev/null 2>&1
}

# Delete the TOML config for this worktree. Idempotent.
warp_remove_tab_config() {
    local wt_path="$1"
    warp_available || return 0

    local target
    target="$(warp_tab_config_path "$wt_path")"
    rm -f "$target" 2>/dev/null
    return 0
}
